### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by brianyeap** [HassanAlthaf/IndoorMaps#1]
Hi, all I want to say is that thank you very much for this awesome project, this is just what I am looking for.

I have a question though, how can I create my own custom map? like how can I know the x and y of it? did you use any tools to create it?

also, the `showHallwayPoints = true;` doesn't show the dots

**Comment by HassanAlthaf** [comment]
Nope, it has to be set manually. The top left corner is X = 0, Y = 0 (origin basically)

**Comment by HassanAlthaf** [comment]
Did you define any hallway points? (Also, multi-floor system hasnt been made yet).

**Comment by brianyeap** [comment]
ah ok, I got it to work now. Thank you very much!

**Comment by brianyeap** [comment]
Really sorry for disturbing you, I am very new to javascript and I have a question. I saw that you used 
```
node.addEventListener("click", function (e) {
    if (mapSelection === null) {
        thisObject.removeRouteIndicators();
        mapSelection = this;
        this.classList.add('selected');
    } else {
        // console.log(mapSelection.dataset.id + " : " + this.dataset.id);
        let paths = thisObject.findPaths(mapSelection.dataset.id, this.dataset.id);

        let shortestPath = thisObject.findShortestPath(paths);

        thisObject.drawPath(shortestPath);

        mapSelection = null;
        this.classList.add('destination');
    }
}
```
to register the clicks by the user to show the path. But how can I make it so that the user doesn't have to click? as in like there will be a provided start ID and end ID in an array. and with for loop it will cycle through all the paths and display it to the user.

Do you have any idea on how I can achieve this? (you can just give me a brief description and I'll try and figure it out)

**Comment by brianyeap** [comment]
hi, any update ?

**Comment by HassanAlthaf** [comment]
` let paths = thisObject.findPaths(mapSelection.dataset.id, this.dataset.id);` 

There you go, the entire paths list. Use `thisObject.drawPath(shortestPath);` to draw.

**Comment by brianyeap** [comment]
Currently, users have to click only it can display it because of the click event listener but how can I make it so that the user doesn't have to click and it'll just display the data I provided? I tried putting `let paths = thisObject.findPaths(7, 3);` outside of the `node.addEventListener("click", function (e) { ... }` but I can't get it to work it says `Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by brianyeap** [comment]
it was because of the door putting the code below the addDoors fixed it. Thank you for helping me!
